import {
  ArrowRight,
  Check,
  Coins,
  Cross,
  ExternalLink,
  FileBadge,
  FolderInput,
  FolderOutput,
  FolderSync,
  Globe,
  Minus,
  Plus,
  Search,
  Wallet,
} from 'lucide-react';
import { Spinner } from './spinner';

export const icons = {
  'arrow-right': ArrowRight,
  check: Check,
  coin: Coins,
  contract: FileBadge,
  cross: Cross,
  'external-link': ExternalLink,
  magnify: Search,
  minus: Minus,
  network: Globe,
  plus: Plus,
  spinner: Spinner,
  'tx-in': FolderInput,
  'tx-out': FolderOutput,
  'tx-self': FolderSync,
  wallet: Wallet,
};
